name: release

on:
  release:
    types: [created]
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - uses: mihails-strasuns/setup-dlang@v1
        with:
          compiler: ldc-1.18.0
      - name: Build qsubarray
        run: cd examples/qsubarray && dub build && cd ../..
      - name: Build qsubxargs
        run: cd examples/qsubxargs && dub build && cd ../..
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'examples/qsubarray/qsubarray examples/qsubxargs/qsubxargs'
