name: release

on:
  release:
    types: [created]
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - uses: mihails-strasuns/setup-dlang@v0.4.1
        with:
          compiler: ldc-1.18.0
      - name: Build qsubarray
        run: cd examples/qsubarray && dub build --single qsubarray.d && cd ../..
      - name: Build qsubxargs
        run: cd examples/qsubxargs && dub build --single qsubxargs.d && cd ../..
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '../examples/qsubarray ../examples/qsubxargs'
